[workspace]
resolver = "3"
members = [
    # Note that builtins-test-intrinsics cannot be a default member because it
    # needs the `mangled-names` feature disabled, while `testcrate` needs it
    # enabled.
    "builtins-test-intrinsics",
    "compiler-builtins",
    "testcrate",
]

default-members = [
    "compiler-builtins",
    "testcrate",
]

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
  'cfg(bootstrap)',
  # #[cfg(bootstrap)]
  'cfg(target_address_width, values("16", "32", "64"))',
]
